# Generated by Django 6.1.1 on 2026-09-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacheraccount_teachingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Student or parent/guardian mobile number for SMS results.', max_length=20),
        ),
    ]
