# Generated by Django 6.1.1 on 2026-09-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='school.classlevel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='school.academicsession')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='school.term')),
            ],
            options={
                'ordering': ['session__name', 'term__id', 'class_level__name'],
                'unique_together': {('session', 'term', 'class_level')},
            },
        ),
    ]
