# Generated by Django 6.1.1 on 2026-09-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_resultaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='form_teacher_comment',
            field=models.CharField(blank=True, choices=[('Excellent Conduct', 'Excellent Conduct — Consistently well-behaved, respectful and responsible.'), ('Good Conduct', 'Good Conduct — Generally well-behaved, respectful and cooperative.'), ('Fair Conduct', 'Fair Conduct — Usually well-behaved but requires occasional guidance and correction.'), ('Needs Improvement', 'Needs Improvement — Requires closer guidance to improve conduct, discipline and cooperation.')], default='', help_text='Behaviour-only comment selected by the Form Teacher.', max_length=30),
        ),
    ]
