# Generated by Django 6.1.1 on 2026-09-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_enrollment_form_teacher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='academic_performance_comment',
            field=models.CharField(blank=True, choices=[('A', 'Excellent academic performance. The student has demonstrated outstanding understanding, effort and achievement. Keep up the excellent work.'), ('B', 'Very good academic performance. The student has shown strong understanding and consistent effort. Greater focus can lead to even better achievement.'), ('C', 'Satisfactory academic performance. The student shows reasonable understanding, but more effort, concentration and consistent study are needed for better results.'), ('D', 'Fair academic performance. The student needs to put in more effort, study more regularly and improve concentration in order to achieve better results.'), ('E_F', 'Academic performance needs significant improvement. The student should work harder, develop better study habits and seek guidance where necessary.')], default='', help_text="Academic performance comment selected by the Form Teacher based on the student's overall grade.", max_length=10),
        ),
    ]
