# Generated by Django 6.1.1 on 2026-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Student or parent/guardian email address for result delivery.', max_length=254),
        ),
    ]
