# Generated by Django 6.1.1 on 2026-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_pin',
            field=models.CharField(blank=True, default='', help_text='Hashed PIN used for student portal login.', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='student_login_active',
            field=models.BooleanField(default=True, help_text='Whether this student can access the student portal.'),
        ),
    ]
