# Generated by Django 6.1.1 on 2026-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_student_login_pin_student_student_login_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, help_text='Student passport photograph.', null=True, upload_to='student_passports/'),
        ),
    ]
